### ISSUE TITLE
Convert betacode files to unicode

### ISSUE THREAD

**Issue by mrgreekgeek** [byztxt/greektext-antoniades#1]
I'm so grateful to Dr. Robinson and others who have made these high-quality files available for free! But let's face it, no one uses betacode any more. So what this repository needs is a folder with the Unicode equivalents of these files. Thanks to @normansimonr, @emg and @countingpine the main [Byzantine text repo](https://github.com/byztxt/byzantine-majority-text) has these in multiple formats, and I'd love to see the rest of the repos here follow suit! 

I'm a pure novice at Python, but I'd love to help with this. To show that I'm serious about this, I've cobbled together a script that converts the `textonly` files to Unicode and adds them to a subfolder of /textonly entitled "unicode." Here's the code, which is intended to be run as `beta_to_uni.py` from the root directory of this repo: 

```
import sys
import unicodedata
import beta_code
import re
import os 

# Define the path to the folder containing the files
folder_path = "../textonly"

# Create a subfolder named "unicode" if it doesn't already exist
if not os.path.exists(os.path.join(folder_path, "unicode")):
    os.makedirs(os.path.join(folder_path, "unicode"))

# List of file names
book_list = [
    "1CO",
    "1JO",
    "1PE",
    "1TH",
    "1TI",
    "2CO",
    "2JO",
    "2PE",
    "2TH",
    "2TI",
    "3JO",
    "AC",
    "COL",
    "EPH",
    "GA",
    "HEB",
    "JAS",
    "JOH",
    "JUDE",
    "LU",
    "MR",
    "MT",
    "PHM",
    "PHP",
    "RE",
    "RO",
    "TIT",
]

# Loop through the file names
for book in book_list:
    # Get the full file path by joining the folder path and file name
    file_path = os.path.join(folder_path, book + '.ANT')

    # Get the filename from the path
    filename = os.path.basename(file_path)
    
    # Read the file
    with open(file_path, "r") as inputfile:
        clean = inputfile.read()
        # Substitute letters to ensure that beta_code properly converts to Unicode
        clean = clean.replace('v', 's')
        clean = clean.replace('c', 'j')               # 1. replacing c with x (using j as a placeholder)
        clean = clean.replace('x', 'c')               # 2. 
        clean = clean.replace('j', 'x')               # 3.
        
        clean = clean.replace('y', 'j')               # 1. replacing y with q (using j as a placeholder)
        clean = clean.replace('q', 'y')               # 2. 
        clean = clean.replace('j', 'q')               # 3. 
                
        # Convert from betacode to unicode using https://github.com/perseids-tools/beta-code-py
        clean = beta_code.beta_code_to_greek(clean)       # convert to unicode Greek letters
        
        # Final cleanup 
        clean = re.sub(r'σ\b', 'ς', clean)                # Fix final sigmas
        clean = re.sub(' --', '\u2014', clean)            # Convert dashes to em dashes
        
        clean = re.sub('\n\n', '\n\u00B6', clean)         # Indicate original paragraphing with a 'pilcrow' (¶)
        clean = re.sub('\n', '', clean)                   # Remove all line breaks
        clean = re.sub('(?<=[0-9])·', ':', clean)         # Fix references that were mangled by beta_code 
        clean = re.sub('(\d+:\d+ )', '\n\\1', clean)      # find all verse beginnings and add a line break before them
        clean = re.sub('(?m)^\n', '', clean)              # Remove extra line break at beginning of file
        clean = re.sub('\u00B6', '\n', clean)             # Restore original paragraphing

    # Save the Unicode text to a file in the "unicode" subfolder
    with open(os.path.join(folder_path, "unicode", book + '.txt'), "w", encoding="utf-8") as outputfile:
        outputfile.write(clean)
```
Obviously parts of this were inspired/copied from the code in the Byzantine Majority text repo. 😄 I'd love to get some feedback on this. Anything I'm missing? Any way to do this more efficiently? Any other suggestions for improvement? Once the script is fine-tuned, I'd love to contribute it to the repo here if someone can tell me how to do it. 
Thanks, and God bless!

**Comment by normansimonr** [comment]
@mrgreekgeek Hey! This is amazing! Thank you so much for taking the time to put this script together! It looks great!

The most efficient way to test the code and incorporate it in the repository is by opening a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). After that, we can comment your code and test it, and convert the beta files into the Unicode versions. And finally, we can merge your code and the Unicode files into the repo and make an official release. I know you're just starting to learn Python, so I don't want to overwhelm you with Git and GitHub, so if you consider you can give it a try, by all means! But if you find yourself struggling with it, just let me know and I can step in and help.

Thanks again!

**Comment by mrgreekgeek** [comment]
Thank you, @normansimonr! I tried creating a pull request... 😄 Did it work?

**Comment by normansimonr** [comment]
@mrgreekgeek Thank you! Looking at it now!
